name: Terraform CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate -no-color -var-file="terraform.tfvars" -var-file="services/demo.tfvars"
